[[main]]
  name = "Projets"
  pageRef = "/projets/"
  weight = 10

[[main]]
  name = "Brainyard"
  pageRef = "/brainyard/"
  weight = 20

[[main]]
  name = "À propos"
  pageRef = "/a-propos/"
  weight = 30
