[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[main]]
  name = "Galerie"
  pageRef = "/galerie/"
  weight = 20

[[main]]
  name = "À propos"
  pageRef = "/a-propos/"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 40
